# Generated by Django 2.1.1 on 2020-04-16 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('zumba class', 'ZUMBA CLASS'), ('swimming class', 'SWIMMING CLASS'), ('basketball match', 'BASKETBALL MATCH'), ('yoga class', 'YOGA CLASS'), ('dancing class', 'DANCING CLASS')], default='zumba class', max_length=100)),
                ('time', models.CharField(choices=[('7:00 am - 8:00 am', '7:00 am - 8:00 am'), ('8:00 am - 9:00 am', '8:00 am - 9:00 am'), ('9:00 am - 10:00 am', '9:00 am - 10:00 am'), ('10:00 am - 11:00 am', '10:00 am - 11:00 am'), ('11:00 am - 12:00 pm', '11:00 am - 12:00 pm'), ('12:00 pm - 1:00 pm', '12:00 pm - 1:00 pm'), ('1:00 pm - 2:00 pm', '1:00 pm - 2:00 pm'), ('2:00 pm - 3:00 pm', '2:00 pm - 3:00 pm'), ('3:00 pm - 4:00 pm', '3:00 pm - 4:00 pm'), ('4:00 pm - 5:00 pm', '4:00 pm - 5:00 pm')], default='7:00 am - 8:00 am', max_length=100)),
                ('location', models.CharField(choices=[('MGS Room 101', 'MGS Room 101'), ('MGS Room 102', 'MGS Room 102'), ('MGS Room 103', 'MGS Room 103'), ('MGS Room 104', 'MGS Room 104'), ('MGS Room 105', 'MGS Room 105')], default='MGS Room 101', max_length=100)),
                ('start_date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_street', models.CharField(max_length=50)),
                ('customer_city', models.CharField(max_length=50)),
                ('customer_state', models.CharField(max_length=50)),
                ('customer_zip', models.CharField(max_length=10)),
                ('customer_email', models.CharField(max_length=50)),
                ('customer_phone', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GymEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('weight', models.CharField(choices=[('5 pound', '5 pound'), ('10 pound', '10 pound'), ('50 pound', '50 pound'), ('100 pound', '100 pound')], default='5 pound', max_length=100)),
                ('customer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='gym.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_street', models.CharField(max_length=50)),
                ('staff_city', models.CharField(max_length=50)),
                ('staff_state', models.CharField(max_length=50)),
                ('staff_zip', models.CharField(max_length=10)),
                ('staff_email', models.CharField(max_length=50)),
                ('staff_phone', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('staff_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='availability',
            name='availability_staff_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='gym.Staff'),
        ),
    ]
